"""add_animal_id_and_confidence_to_cattle_detections

Revision ID: 3e68f74c6163
Revises: e4266c518475
Create Date: 2025-12-06 12:07:38.387456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e68f74c6163'
down_revision: Union[str, Sequence[str], None] = 'e4266c518475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cattle_detections', sa.Column('animal_id', sa.String(length=50), nullable=False))
    op.add_column('cattle_detections', sa.Column('confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_cattle_detections_animal_id'), 'cattle_detections', ['animal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cattle_detections_animal_id'), table_name='cattle_detections')
    op.drop_column('cattle_detections', 'confidence')
    op.drop_column('cattle_detections', 'animal_id')
    # ### end Alembic commands ###
