"""delete_animal_table

Revision ID: d72464474f3a
Revises: e5b34ff4d435
Create Date: 2025-11-28 00:00:47.632903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd72464474f3a'
down_revision: Union[str, Sequence[str], None] = 'e5b34ff4d435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. СНАЧАЛА удаляем зависимость (Foreign Key) и колонку
    # Обрати внимание: имя констрейнта 'weighings_animal_id_fkey' должно совпадать с тем, что в ошибке
    op.drop_constraint('weighings_animal_id_fkey', 'weighings', type_='foreignkey')
    op.drop_column('weighings', 'animal_id')

    # 2. Добавляем колонки в другие таблицы (это можно делать параллельно)
    op.add_column('user_reports', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_reports', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # 3. И только В КОНЦЕ удаляем саму таблицу
    op.drop_table('animals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. При откате СНАЧАЛА восстанавливаем таблицу (иначе FK некуда будет ссылаться)
    op.create_table('animals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('animals_pkey'))
    )

    # 2. Убираем добавленные колонки
    op.drop_column('user_reports', 'updated_at')
    op.drop_column('user_reports', 'created_at')

    # 3. Возвращаем колонку и связь В КОНЦЕ
    op.add_column('weighings', sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('weighings_animal_id_fkey'), 'weighings', 'animals', ['animal_id'], ['id'])
    # ### end Alembic commands ###