"""drop user_reports add user_id to reports

Revision ID: e054cc6f2f5d
Revises: 3e68f74c6163
Create Date: 2025-12-21 23:48:11.838699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e054cc6f2f5d'
down_revision: Union[str, Sequence[str], None] = '3e68f74c6163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_table('user_reports')
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE reports SET user_id = (SELECT MIN(id) FROM users LIMIT 1)")
    op.add_column('reports', sa.Column('name', sa.String(length=25), nullable=False))
    op.alter_column('reports', 'user_id', nullable=False)
    op.create_foreign_key(
        'reports_user_id_fkey',
        'reports',
        'users',
        ['user_id'],
        ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'user_id')
    op.drop_column('reports', 'name')
    op.create_table('user_reports',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('user_reports_report_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'report_id', name=op.f('user_reports_pkey'))
    )
    # ### end Alembic commands ###
