"""remove animal_types table and type_id from animals

Revision ID: e5b34ff4d435
Revises: e75ab9e3602e
Create Date: 2025-11-03 19:19:48.041084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5b34ff4d435'
down_revision: Union[str, Sequence[str], None] = 'e75ab9e3602e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала удаляем внешний ключ и колонку
    op.drop_constraint(op.f('animals_type_id_fkey'), 'animals', type_='foreignkey')
    op.drop_column('animals', 'type_id')
    # Затем удаляем таблицу
    op.drop_table('animal_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('animals_type_id_fkey'), 'animals', 'animal_types', ['type_id'], ['id'])
    op.create_table('animal_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('animal_types_pkey')),
    sa.UniqueConstraint('type', name=op.f('animal_types_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
