"""add reports and user_reports tables

Revision ID: e75ab9e3602e
Revises: 9bd38195711a
Create Date: 2025-11-03 18:22:01.918692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75ab9e3602e'
down_revision: Union[str, Sequence[str], None] = '9bd38195711a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('reports', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('reports', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.drop_constraint(op.f('reports_url_key'), 'reports', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('reports_url_key'), 'reports', ['url'], postgresql_nulls_not_distinct=False)
    op.alter_column('reports', 'url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('reports', 'updated_at')
    op.drop_column('reports', 'created_at')
    # ### end Alembic commands ###
